language: csharp
mono: none
dotnet: 2.1.502
solution: Cactus.Blade.Serialization.XSerializer.sln
install:
  - dotnet restore
script:
  - dotnet msbuild /p:Configuration=Release Cactus.Blade.Serialization.XSerializer.sln
  - dotnet restore
  - dotnet test Serialization.XSerializer.Test/Serialization.XSerializer.Test.csproj
